import Head from "next/head";
import { useEffect, useState, useLayoutEffect } from "react";
import Root from "../components/Root";

function useWindowHeight() {
  const [height, setHeight] = useState(0);
  useEffect(() => {
    function updateSize() {
      setHeight(window.innerHeight);
    }
    window.addEventListener("resize", updateSize);
    updateSize();
    return () => window.removeEventListener("resize", updateSize);
  }, []);
  return height;
}

export default function Home() {
  const height = useWindowHeight();
  return (
    <div
      id="root"
      className={"text-gray-300 bg-black w-screen"}
      style={{ height: height }}
    >
      <Head>
        <title>Battle Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Root />
    </div>
  );
}
