import Head from "next/head";
import { useEffect, useState } from "react";
import BattleSimulator from "../components/BattleSimulator";

export default function Home() {
  return (
    <div id="root" className={"text-gray-300 bg-black w-screen h-screen"}>
      <Head>
        <title>Battle Simulator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BattleSimulator />
    </div>
  );
}
